### ISSUE TITLE
Inquiry Regarding the Inclusion of Transferability Recovery Articles in Your Survey

### ISSUE THREAD

**Issue by xychendave** [YuheD/awesome-model-transferability-estimation#1]
Hello,

I would like to inquire about your perspective on a few articles related to transferability in recovery:

DEPARA: Deep Attribution Graph for Deep Knowledge Transferability
DataMap: Dataset Transferability Map for Medical Image Classification
ModelGiF: Gradient Fields for Model Functional Distance
It seems that I haven't seen these articles included in the survey. I'm curious if you've come across these works and what your considerations might be for not incorporating them into the repository.

Thank you for your time and insight.

**Comment by YuheD** [comment]
Thank you for your interest in our survey. 
We think the goal of these three papers can be considered as establishing a task or dataset map similar to Taskonomy [1], which typically does not consider specific target datasets but instead builds a similarity map within an existing model zoo or dataset zoo. 

The "model transferability estimation" task in our survey focuses on the issue of proposing a metric for a given target dataset, which is a relatively smaller problem, hence these papers were not included at this time. 
We briefly described the difference in the section on task transferability in related work, sorry for not explaining it clearly, and we will further improve the paper.

In fact, we also considered a more comprehensive survey to include these articles initially, but due to conference page limits, we only included papers related to this smaller issue.  A  comprehensive survey is our future work.


[1] Taskonomy: Disentangling task transfer learning

**Comment by YuheD** [comment]
I noticed that you have closed the issue, hoping your concerns have been addressed. 
If you have any further questions, feel free to contact me.

**Comment by xychendave** [comment]
Thanks for the detail reply. I see the differences between the three papers we discussed and your survey so I close the issue after I created. I also noticed the inclusion of another gradient attribution method paper in your references, which addresses my concerns. Appreciate for your effort and responds. Thanks again
